import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
    header: {
      marginTop: 0,
      width: '100%',
      height: 90,
      paddingRight: 15,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    logo_text: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      paddingLeft: 10,
    },
    logo: {
      width: '28%',
      height: 50,
      marginRight: 10,
      backgroundColor: '#fff',
      borderRadius: 60,
    },
    textoLogo: {
      fontSize: 17,
      fontWeight: '600',
      color: '#fff',
    },
    btnBurguer: {
      width: '15%',
      height: 60,
      justifyContent: 'center',
      alignItems: 'center',
    },
    backdropPressable: {
        position: 'absolute',
        top: 0,
        left: '80%',
        width: '20%',
        height: '100%',
        zIndex: 99,
        elevation: 20,
    },
    backdrop: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 98,
        elevation: 20,
    },
    sideMenu: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '80%',
        height: '100%',
        backgroundColor: '#474747',
        padding: 0,
        zIndex: 98,
        elevation: 20,
    },
    menuContainer: {
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
    },
    userContainer: {
      width: '100%',
      height: 150,
      backgroundColor: '#aaaeb6',
      paddingTop: 0,
      paddingLeft: '5%',
      flexDirection: 'row',
      alignItems: 'center',
    },
    userImageContainer: {},
    userImage: {
      width: 70,
      height: 70,
    },
    userNameContainer: {},
    userName: {
      color: '#fff',
      fontSize: 20,
      fontWeight: '600',
      marginLeft: 8,
    },
    optionsContainer: {
      marginTop: 30,
      width: '100%',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
    },
    optionPendientes:{
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignContent: 'center',
      alignSelf: 'center',
      marginBottom: 20,
      marginLeft: 15,
    },
    optionPendientes2:{
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    subPendientesContainer: {
      width: '100%',
      flexDirection: 'column',
      justifyContent: 'flex-end',
      alignItems: 'flex-start',
      alignContent: 'center',
      alignSelf: 'center',
      marginBottom: 10,
      marginLeft: '50%',
      overflow: 'hidden',
    },
    subOptionsContainer: {
      marginBottom: 20,
    },
    textSubPendientes: {
      color: '#fff',
      fontSize: 20,
      marginLeft: 15,
    },
    optionAutorizados:{
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignContent: 'center',
      alignSelf: 'center',
      marginBottom: 20,
      marginLeft: 15,
    },
    optionAutorizados2:{
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    subAutorizadosContainer: {
      width: '100%',
      flexDirection: 'column',
      justifyContent: 'flex-end',
      alignItems: 'flex-start',
      alignContent: 'center',
      alignSelf: 'center',
      marginBottom: 10,
      marginLeft: '50%',
      overflow: 'hidden',
    },
    textSubAutorizados: {
      color: '#fff',
      fontSize: 20,
      marginLeft: 15,
    },
    optionContainer: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      alignContent: 'center',
      alignSelf: 'center',
      marginBottom: 20,
      marginLeft: 15,
    },
    optionIcon: {},
    menuText: {
      color: '#fff',
      fontSize: 28,
      marginLeft: 8,
    },
    componentContainer: {
      marginBottom:130,
        padding: 10,

    },
  });

  export default styles;